### PR TITLE
Desgen Website UI  design

### LINKED ISSUE #94: Contest: Make Ui design for Desgen Website
## Description
**Create Ui design for Desgen Website**

```
You only have to make designs , no need to code it. 

It will be a static website for now.
It will contain the designs and other information about the platform

``` 

**This is an open contest , so you don't have to get assigned . Do not comment until your design is ready .First you have create design for the whole platform**

**Then Comment on the issue  with the given details**

```
Name : 
Design Link :  
Discord username : "example - shìtìz#7676"
```
**You can work on any software - Figma, AdobeXD, Framer etc**

**Don't create any pull request , You have to only comment on the issue with your design link ( do not add photos in the comment section )**

**Best 3-5 designs will be allowed to make a pull request and will be merged with level-3 label**

**Any doubts or issues will be resolved on discord**

### PR DESCRIPTION
**Pull request by vaibhavpathak999**
## Description

I have designed UI design for Desgen Website.  I am creating a folder named Vaibhav_Glassmorphism inside Design->Website folders.

## Related Issue

Fixes #94

## Type of Change:

- [x] Ui/Ux
- [ ] Coding
- [ ] Documentation
- [x] Other : UI/ UX designing

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.
- [x] I have performed a self-review of my own code/design.
- [x] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [x] My UI is responsive
- [x] UI made is my unique or issued by the project maintainers

### Screenshots (if appropriate):
Web 1920 – 1
Web 1920 – 2
Web 1920 – 5

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@vaibhavpathak999 Read this
 https://github.com/awantika10/Desgen/blob/gssoc/Contribution/CONTRIBUTING.md#submissions

**Review by SHITIZ-AGGARWAL — CHANGES_REQUESTED** [review]
@vaibhavpathak999 Read this
https://github.com/awantika10/Desgen/blob/gssoc/Contribution/CONTRIBUTING.md#submissions

Remove readme and add the html file

If you face any problem, ping me on discord

**Comment by vaibhavpathak999** [comment]
@SHITIZ-AGGARWAL  I have made the required changes. Please review it.

**Review by SHITIZ-AGGARWAL — APPROVED** [review]

**Comment by SHITIZ-AGGARWAL** [comment]
@vaibhavpathak999  Thank you for your contribution 🎉

**Pull request merged**
