### PR TITLE
3=D animation and illustrations

### PR DESCRIPTION
**Pull request by chiragagrawal9200**
## Description
Made a illustration on an idea of medicine schedule i.e. Medicine check app
Made little illustrations of medicine
## Related Issue

#3 
## Type of Change:

- [ ] Ui/Ux
- [ x] Coding
- [ ] Documentation
- [x] Other : 

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.
- [x] I have performed a self-review of my own code/design.
- [x] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [ ] My UI is responsive
- [ ] UI made is my unique or issued by the project maintainers

### CODE REVIEW

**Comment by chiragagrawal9200** [comment]
@SHITIZ-AGGARWAL @awantika10 is this okay now?

**Comment by weebo-ary** [comment]
You have to make the folder of your name if you have not added your name inside the design.

**Comment by weebo-ary** [comment]
Do these changes because without it we are unable to determine about the designer of that illustration......

**Comment by weebo-ary** [comment]
This is the last change @chiragagrawal9200 after that we will merge your PR for sure !!

**Comment by SHITIZ-AGGARWAL** [comment]
@chiragagrawal9200 you still have added images in contribution please that also and add it in the designs folder only

**Comment by chiragagrawal9200** [comment]
> @chiragagrawal9200 you still have added images in contribution please that also and add it in the designs folder only

No.... this time I added in the design folder

**Pull request closed without merging**
