### PR TITLE
Added Idea-2 In ideas.md

### PR DESCRIPTION
**Pull request by rohan-kulkarni-25**
## Description
Adding design idea for the ideas.md

## Idea number
002

### Description 
This is an Idea for Application Named "WE ARE SAFE !!".

This app will allow everyone of us to be safe or alert anywhere we are.In this app we will create a account same as google account.We can add family members to this account.
If any of family member is in emergency then with just a single click his location will be shared with his family members and local police.This will not only help girls/women to be safe but also help everyone in case of medical emergency.

### Features
 - 1.Contacts Police and Added Family member in case of Emergency
 - 2.Will help your location to get shared till police and Family only 
 - 3.Login/Signup Feature 
 - 4.Just single click alert 

## Type of Change:

- [x] Documentation
- [x] Other : Adding design idea for the ideas.md

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.

### CODE REVIEW

**Comment by rohan-kulkarni-25** [comment]
Please give a Review @SHITIZ-AGGARWAL

**Comment by Sloth-Panda** [comment]
@rohank2502 bro before making a pr make an issue first and ask to get assigned if you get assigned then you should make a pr else not.

**Comment by rohan-kulkarni-25** [comment]
@Sloth-Panda  @SHITIZ-AGGARWAL told me that this issue is open and no need to assign create a pull request directly

**Comment by SHITIZ-AGGARWAL** [comment]
@rohank2502 Always keep in mind to mention the issue on the top for which a pr is made 
`Fixes #issue_number`
I have made this change for now but remember to do this in future

**Comment by SHITIZ-AGGARWAL** [comment]
@Sloth-Panda Please refer the issue first before commenting 😊

**Comment by rohan-kulkarni-25** [comment]
> @rohank2502 Always keep in mind to mention the issue on the top for which a pr is made
> `Fixes #issue_number`
> I have made this change for now but remember to do this in future

Ook I will keep in mind from next time thanks 😊

**Comment by SHITIZ-AGGARWAL** [comment]
@rohank2502 The template is little bit changed, you can see the new template you also have to add your name in the idea
image

**Comment by SHITIZ-AGGARWAL** [comment]
Conflicts arise when you don't update your repo, this is also important

**Comment by rohan-kulkarni-25** [comment]
> new template you also have to add your name in the idea

Ok i will do it now

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Conflicts arise when you don't update your repo, this is also important

ook so what should i have to do now ?

**Comment by SHITIZ-AGGARWAL** [comment]
Either you can make a new pull request from a new branch or update this branch and then rebase your commits

**Comment by rohan-kulkarni-25** [comment]
> new branch or update this branch and then rebase your commits

I will make a new PR tomarrow by updating by repo it will raise no conflicts then right ? and also make pr with new templates !!

**Comment by SHITIZ-AGGARWAL** [comment]
> > new branch or update this branch and then rebase your commits
> 
> I will make a new PR tomarrow by updating by repo it will raise no conflicts then right ? and also make pr with new templates !!

yes you can make a new pr , pr template is same I am talking about the idea submission template (you also have to add name).
Also creating a new pr is not the ideal solution , it is not preferred but since it is your beginning we can start easy. The ideal approach is to rebase your commits

**Comment by Sloth-Panda** [comment]
> @Sloth-Panda Please refer the issue first before commenting 😊

Hey sorry but I thought as there were no issues also no issues linked to this  pr so said so

**Comment by SHITIZ-AGGARWAL** [comment]
> > @Sloth-Panda Please refer the issue first before commenting 😊
> 
> Hey sorry but I thought as there were no issues also no issues linked to this pr so said so

no problem 👍

**Comment by rohan-kulkarni-25** [comment]
I have created a new pull request please give it a review @SHITIZ-AGGARWAL

**Pull request closed without merging**
