### PR TITLE
Added Idea 16

### PR DESCRIPTION
**Pull request by madhhuurrii**
## Description
Added idea 16

## Related Issue

Fixes #8  

## Type of Change:

- [ ] Ui/Ux
- [ ] Coding
- [x] Documentation
- [ ] Other : 

## Checklist:

- [ ] Pull request is made against `gssoc` branch.
- [ ] My code/design follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code/design.
- [ ] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [ ] My UI is responsive
- [ ] UI made is my unique or issued by the project maintainers

### CODE REVIEW

**Comment by madhhuurrii** [comment]
Hey! @SHITIZ-AGGARWAL, please review my PR

**Comment by SHITIZ-AGGARWAL** [comment]
@madhhuurrii This idea is copied ?

**Comment by madhhuurrii** [comment]
No, this idea was something I wanted to work on so had created a draft for the abstract of the project. But didn't really started working. @SHITIZ-AGGARWAL

**Comment by Shweta200126** [comment]
Are you sure @madhhuurrii? coz I was in this hackathon where local.ly was built, https://devpost.com/software/local-ly and were winners as well. Don't do this for getting a pr merged.

**Pull request closed without merging**
