### PR TITLE
Rohank2502 idea 001

### PR DESCRIPTION
**Pull request by rohan-kulkarni-25**
## Description
Adding design idea for the ideas.md

## Idea number
001

### Description 
This is an Idea for Application Named "WE ARE SAFE !!".

This app will allow everyone of us to be safe or alert anywhere we are.In this app we will create a account same as google account.We can add family members to this account.
If any of family member is in emergency then with just a single click his location will be shared with his family members and local police.This will not only help girls/women to be safe but also help everyone in case of medical emergency.

### Features
 - 1.Contacts Police and Added Family member in case of Emergency
 - 2.Will help your location to get shared till police and Family only 
 - 3.Login/Signup Feature 
 - 4.Just single click alert 

## Type of Change:

- [x] Documentation
- [x] Other : Adding design idea for the ideas.md

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.

### CODE REVIEW

**Comment by awantika10** [comment]
@rohank2502 Please add the details which are mentioned on the PR templete

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 Please add the details which are mentioned on the PR templete

@awantika10  Ok Actually I have attached a file in which i have did but no issues i will add it in comment also.

**Comment by SHITIZ-AGGARWAL** [comment]
@rohank2502 you have to fill the template which was given



## Description



## Related Issue

closes #[issue_number] 

## Type of Change:



- [ ] Ui/Ux
- [ ] Coding
- [ ] Documentation
- [ ] Other : 

## Checklist:

- [ ] Pull request is made against `gssoc` branch.
- [ ] My code/design follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code/design.
- [ ] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [ ] My UI is responsive
- [ ] UI made is my unique or issued by the project maintainers

### Screenshots (if appropriate):

**Comment by SHITIZ-AGGARWAL** [comment]
you can see #11 for reference

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> you can see #11 for reference

Ok Thanks I will Update the request soon !!

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> you can see #11 for reference

I dont have my flow ready !! I thought it was just to give an idea so I make a PR regarding Idea

**Comment by SHITIZ-AGGARWAL** [comment]
@rohank2502 The issue is for idea only you have to tell the description and other details about the Pull request for example


## Description

Adding design idea for the ideas.md

Idea : An app that will allow everyone of us to be safe or alert anywhere we are.

## Related Issue

closes #8 

## Type of Change:

- [x] Documentation

and so on filling other required areas as mentioned in the template

**Comment by rohan-kulkarni-25** [comment]
@SHITIZ-AGGARWAL  I have done changes Please give it a review

**Comment by SHITIZ-AGGARWAL** [comment]
@rohank2502 You don't have to create a new file. Update your idea in ideas.md file only . This template was for pr template the one which is at the top of the comments  [this one](https://github.com/awantika10/Desgen/pull/10#issue-587491464)

You have filled it correctly now ,just update idea in the ideas.md file properly that will do

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 You don't have to create a new file. Update your idea in ideas.md file only . This template was for pr template the one which is at the top of the comments [this one](https://github.com/awantika10/Desgen/pull/10#issue-587491464)
> 
> You have filled it correctly now ,just update idea in the ideas.md file properly that will do

Okk means One idea is present there already i should just update and give idea no 2 to my  idea right ? And should i make new PR or no with this only

**Comment by SHITIZ-AGGARWAL** [comment]
Yes , you have to add your idea in that only as number 2 (like the idea-1 is written) . You can commit in this pr only or if you are having trouble you can create a new pr(for that you have to make a new branch)

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Yes , you have to add your idea in that only as number 2 (like the idea-1 is written) . You can commit in this pr only or if you are having trouble you can create a new pr(for that you have to make a new branch)

Ok i will close  this PR and create a new pr with new idea and also delete the file idea created by me

**Pull request closed without merging**
