### PR TITLE
Added Idea 1 

### PR DESCRIPTION
**Pull request by rohan-kulkarni-25**
## Description

Added Idea 1 in idea.md 

## Related Issue

Fixes #8  

## Type of Change:
- [x] Documentation
- [x] Other : Idea 

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.
- [x] I have performed a self-review of my own code/design.

### CODE REVIEW

**Review by SHITIZ-AGGARWAL — APPROVED** [review]

**Comment by SHITIZ-AGGARWAL** [comment]
Good work @rohank2502 🎉

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Good work @rohank2502 🎉

Thanks @SHITIZ-AGGARWAL  You guided me well

**Review by awantika10 — APPROVED** [review]
Good work @rohank2502

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Good work @rohank2502

Thanks @awantika10

**Comment by starrohan999** [comment]
hii @SHITIZ-AGGARWAL, I have an idea so can you please assign it to me.

**Pull request merged**
