### PR TITLE
Update Ideas.md

### PR DESCRIPTION
**Pull request by ASLManasa**
## Description

The Design is a web application on competetive programming contests in one place.

## Related Issue

Fixes #8 >

## Type of Change:

- [ ] Ui/Ux
- [ ] Coding
- [x ] Documentation
- [ ] Other : 
## Checklist:

- [ x] Pull request is made against `gssoc` branch.
- [ x] My code/design follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code/design.
- [ ] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [ ] My UI is responsive
- [ ] UI made is my unique or issued by the project maintainers

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@ASLManasa Remove ## before your name

**Comment by ASLManasa** [comment]
ok sir

**Comment by ASLManasa** [comment]
done sir @SHITIZ-AGGARWAL

**Review by SHITIZ-AGGARWAL — APPROVED** [review]

**Review by awantika10 — APPROVED** [review]
Good work!

**Comment by ASLManasa** [comment]
@awantika10  Thank you mam.

**Comment by SHITIZ-AGGARWAL** [comment]
Thank you for your contribution 🚀

**Pull request merged**
