### PR TITLE
Added logo design

### LINKED ISSUE #102: Feat: Logo_for_Desgen
**What is your feature request related to ?**

- [x] Desgen Website
- [x] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**

Make a logo for Desgen website which should be :

1. Attractive.
2. Colorful.
3. Related to our Theme.

**For any Doubts regarding this issue you can ask in Discord Server !!**

### PR DESCRIPTION
**Pull request by ambivert-sam**
I made 3 logos design for Desgen

Fixes #102 

## Type of change
Other: Made 3 designs logo included the tag line in the logo "innovation starts with people"

## Checklist:

- [✔ ] Pull request is made against `gssoc` branch.
- [✔] My code/design follows the style guidelines of this project.
- [✔] I have performed a self-review of my own code/design.

White with Colorful Triangles Internet Logo (1)

Medium Violet Square Real Estate Logo

brand_logo

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@ambivert-sam your repo is not updated thus you are not able to see the logo folder, either update your repo or go to [this folder](https://github.com/awantika10/Desgen/tree/gssoc/Designs/Desgen_Logo) and add your png directly(this will create a new updated branch with a new pr)

**Review by SHITIZ-AGGARWAL — CHANGES_REQUESTED** [review]
If you face any problem in this, then ping me on discord

**Comment by ambivert-sam** [comment]
While uploading a file it's showing like this @SHITIZ-AGGARWAL 
Screenshot (169)

**Comment by SHITIZ-AGGARWAL** [comment]
@ambivert-sam You must be getting an option of creating a new pull request

**Comment by ambivert-sam** [comment]
> @ambivert-sam You must be getting an option of creating a new pull request

No, I'm not getting such an option please guide me I don't know how to do it

**Comment by SHITIZ-AGGARWAL** [comment]
@ambivert-sam 
Go to   designs -> Desgen_Logo
Then follow this
image
image

**Comment by ambivert-sam** [comment]
@SHITIZ-AGGARWAL I did the same thing as you told but while I go on upload files I get this "Uploads are disabled.
File uploads require push access to this repository" I send you the screenshot also maybe access is not provided to me 
Please tell me what to do next

**Comment by ambivert-sam** [comment]
> While uploading a file it's showing like this @SHITIZ-AGGARWAL Screenshot (169)

This is the screenshot

**Comment by SHITIZ-AGGARWAL** [comment]
@ambivert-sam Can you join voice channel on discord

**Comment by SHITIZ-AGGARWAL** [comment]
@ambivert-sam join discord voice channel at 5:00 pm

**Comment by ambivert-sam** [comment]
> @ambivert-sam join discord voice channel at 5:00 pm

okay

**Comment by ambivert-sam** [comment]
@SHITIZ-AGGARWAL Thank you for the guidance you can check once I made the PR

**Pull request closed without merging**
