### PR TITLE
Cp Ui-part1

### LINKED ISSUE #56: Feat: Make UI for a website that notifies about cp competitions (idea-6)
**What is your feature request related to ?**

- [x] Designing

**Description**

Maki ui design for a website that notifies all the competitive programming competitions
The design should be made using new ui technology trends 
like Glassmorphism , Neumorphism , Retro aesthetic , 3d graphics etc

`Please mention the technology you will be using to solve this issue in comments`

You can use any software you are comfortable with like Figma, AdobXD , framer etc

**Describe the solution you'd like**

```
Description
A website that notifies all the competitive programming competitions going on and upcoming. We don't find an application where we get all the information about competitive coding at the same time. This will help aspirants to be updated in one place.

Add the description about the idea and add the features for the idea or how to implement the idea.

Features
Login Page
Signup page
selection of websites to be shown.
reminder to Gmail.
Blogs about how to move ahead with cp.
practice questions all diffrent cp topics.

```
You can also add your features in it

**Additional context**

Please give updates of your work at least once in every 3 days ,else the issue will be assigned to others. 
Before making the final PR please ask first

### PR DESCRIPTION
**Pull request by ishu184**
## Related Issue

Fixes #56  

## Type of Change:

- [x] Ui/Ux
- [ ] Coding
- [ ] Documentation
- [ ] Other : 

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.
- [x] I have performed a self-review of my own code/design.
- [ ] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [ ] My UI is responsive
- [x] UI made is my unique or issued by the project maintainers

### CODE REVIEW

**Comment by ishu184** [comment]
@SHITIZ-AGGARWAL I made a pull request please have a look.

**Comment by SHITIZ-AGGARWAL** [comment]
@ishu184 The pngs are good , just add the html file

**Review by SHITIZ-AGGARWAL — CHANGES_REQUESTED** [review]
@ishu184 The pngs are good , just add the html file . 
[Template](https://github.com/awantika10/Desgen/blob/gssoc/Designs/DesignTemplate_IdeaName.html)

Add yours and @ASLManasa name in that

**Comment by SHITIZ-AGGARWAL** [comment]
@ishu184 please give an update.

**Comment by SHITIZ-AGGARWAL** [comment]
@ishu184 Any update

**Review by SHITIZ-AGGARWAL — APPROVED** [review]
@ishu184 Good Work 🎉 
Thank you for your contribution

**Pull request merged**
