### PR TITLE
3d animation and illustration

### PR DESCRIPTION
**Pull request by chiragagrawal9200**
made a illustration on an idea of medicine schedule i.e. Medicine check app
Made little illustrations of medicine

## Related Issue

#3 

## Type of Change:

- [x] like graphic designing

## Checklist:

- [ yes] Pull request is made against `gssoc` branch.
- [yes ] My code/design follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code/design.
- [ ] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [ ] My UI is responsive
- [ ] UI made is my unique or issued by the project maintainers

### CODE REVIEW

**Comment by awantika10** [comment]
@chiragagrawal9200 Which folder you have committed your illustrations?

**Comment by chiragagrawal9200** [comment]
@awantika10 contribution folder

**Comment by awantika10** [comment]
> @awantika10 contribution folder

You need to make a separate folder inside designs folder and so on. Please carefully read the guidelines given in contributing.md. ( Refer design contributions)

**Comment by awantika10** [comment]
@chiragagrawal9200 Also, Are the illustrations made by you?

**Comment by chiragagrawal9200** [comment]
@awantika10 when i am cloning the repo i am not getting the design folder

**Comment by chiragagrawal9200** [comment]
> @chiragagrawal9200 Also, Are the illustrations made by you?

yess

**Comment by awantika10** [comment]
> @awantika10 when i am cloning the repo i am not getting the design folder

@SHITIZ-AGGARWAL please check this

**Comment by SHITIZ-AGGARWAL** [comment]
@chiragagrawal9200 your repo is not updated

**Comment by SHITIZ-AGGARWAL** [comment]
first you have to update your forked repo then pull/fetch the updates in your clone repo then you will be able to see design folder

**Comment by chiragagrawal9200** [comment]
@SHITIZ-AGGARWAL Okay ....  so i need to generate pr again?

**Comment by SHITIZ-AGGARWAL** [comment]
The other way is that you can go to designs folder in awantika10/Desgen and then go to add files make a new file 
then type your design name / your design name .html (this will create a folder of your design name and place a html file in it) and then add your idea following the html template given [template](https://github.com/awantika10/Desgen/blob/gssoc/Designs/DesignTemplate_IdeaName.html) . After this propose the changes, this will create a new updated branch in your repo. Then go to your repo, select that branch and go to your design name folder in designs and upload photos in it

**Comment by SHITIZ-AGGARWAL** [comment]
> @SHITIZ-AGGARWAL Okay .... so i need to generate pr again?

Yes

**Pull request closed without merging**
