### PR TITLE
Desgen Logo Designs Directory and Submission

### LINKED ISSUE #102: Feat: Logo_for_Desgen
**What is your feature request related to ?**

- [x] Desgen Website
- [x] Designing
- [ ] Documentation
- [ ] Others[please specify like testing, code etc]

**Description**

Make a logo for Desgen website which should be :

1. Attractive.
2. Colorful.
3. Related to our Theme.

**For any Doubts regarding this issue you can ask in Discord Server !!**

### PR DESCRIPTION
**Pull request by vaibhavpathak999**
## Description

Changes:
1.) The directory (folder) by the name "Logo Design" is made so that participants can put their logo designs.
2.) Have made a submission by the name "Logo Desgen Vaibhav". 

About Submission: 
Logo design is a single Letter D design made in Photoshop. 
It is folded striped giving it beautiful shadows and a 3D effect. 
Color on each stripe is a gradient of two colors from VIBGYOR which makes it Vibrant, Colorful, and Feel of Freshness.
It has some oily shade to look more smooth and some textured stripes.

## Related Issue

Fixes #102 

## Type of Change:

- [x] Ui/Ux
- [ ] Coding
- [ ] Documentation
- [x] Other : logo designing 

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.
- [x] I have performed a self-review of my own code/design.
- [x] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).
- [ ] My UI is responsive
- [x] UI made is my unique or issued by the project maintainers

### Screenshots (if appropriate):

Logo Design Folder
Logo Desigen Submission

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@vaibhavpathak999 We are planning to get more logos for now , after then depending on the logos we will see if a folder is required for logos specifically or shall we directly choose a logo from the present ones

**Review by SHITIZ-AGGARWAL — COMMENTED** [review]
> @vaibhavpathak999 We are planning to get more logos for now , after then depending on the logos we will see if a folder is required for logos specifically or shall we directly choose a logo from the present ones

@awantika10 is this fine ?

**Comment by awantika10** [comment]
> > @vaibhavpathak999 We are planning to get more logos for now , after then depending on the logos we will see if a folder is required for logos specifically or shall we directly choose a logo from the present ones
> 
> @awantika10 is this fine ?

Yeah

**Comment by pareekakshat** [comment]
Well , I am keen to make a logo for you as I have a experience of making logo as i have made a logo for a coaching institute, my youtube channel, my non profitable organization called 'Ibtida'.
Hence would like to to work on this.

**Pull request closed without merging**
