### PR TITLE
Ideas for Cryptocurrency app

### PR DESCRIPTION
**Pull request by arnab031**
## Description

Ideas for creating an app for investing in cryptocurrency.

## Type of Change:

- [x] Documentation

## Checklist:

- [x] Pull request is made against `gssoc` branch.
- [x] My code/design follows the style guidelines of this project.

### CODE REVIEW

**Review by awantika10 — APPROVED** [review]
Good work ! @arnab031

**Comment by arnab031** [comment]
Thanks Ma'am. @awantika10

**Review by SHITIZ-AGGARWAL — APPROVED** [review]

**Comment by SHITIZ-AGGARWAL** [comment]
Great work 🚀  @arnab031

**Comment by arnab031** [comment]
> Great work 🚀 @arnab031

Thanks sir.

**Pull request merged**
